version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=p7_db
      - MYSQL_ROOT_PASSWORD=mystrongpassword
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  db-data:
